In [1]:
### Bibliotecas para conexão com BD
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

In [2]:
### Engine para ativar o sqlalchemy e fazer as comunicações com BD
engine = create_engine('postgresql+psycopg2://user_gs:udig78ujghs@54.94.241.13/gsc', echo=False)
Session = sessionmaker(bind = engine)

In [3]:
## Qual a quantidade de respondentes de cada país?
session = Session()
result = session.execute(
    ' SELECT p.nome, COUNT(r.index) '\
    ' FROM pais p LEFT OUTER JOIN respondente r ON p.index = r.pais_index ' \
    ' GROUP BY p.nome ' \
    ' ORDER BY p.nome '
)
print('Quantidade de respondentes por país')
for row in result:
    print(row)

Quantidade de respondentes por país
('-', 29)
('Afghanistan', 2)
('Albania', 5)
('Algeria', 5)
('Andorra', 5)
('Angola', 1)
('Argentina', 52)
('Armenia', 5)
('Australia', 194)
('Austria', 72)
('Azerbaijan', 6)
('Bahrain', 1)
('Bangladesh', 58)
('Belarus', 31)
('Belgium', 80)
('Bolivia', 2)
('Bosnia and Herzegovina', 5)
('Botswana', 1)
('Brazil', 255)
('Bulgaria', 44)
('Cambodia', 6)
('Cameroon', 1)
('Canada', 360)
('Chile', 28)
('China', 92)
('Colombia', 33)
('Congo, Republic of the...', 1)
('Costa Rica', 11)
('Croatia', 25)
('Cuba', 5)
('Cyprus', 8)
('Czech Republic', 72)
('Denmark', 66)
('Dominican Republic', 11)
('Ecuador', 5)
('Egypt', 33)
('El Salvador', 3)
('Estonia', 23)
('Ethiopia', 4)
('Fiji', 1)
('Finland', 59)
('France', 278)
('Georgia', 7)
('Germany', 655)
('Ghana', 1)
('Greece', 55)
('Guatemala', 3)
('Honduras', 1)
('Hong Kong (S.A.R.)', 22)
('Hungary', 39)
('Iceland', 2)
('India', 1124)
('Indonesia', 50)
('Iran, Islamic Republic of...', 89)
('Iraq', 1)
('Ireland', 63)
('Israel', 101)
('Italy', 166)
('Jamaica', 1)
('Japan', 39)
('Jordan', 5)
('Kazakhstan', 12)
('Kenya', 14)
('Kuwait', 1)
('Kyrgyzstan', 4)
('Latvia', 19)
('Lebanon', 12)
('Liechtenstein', 2)
('Lithuania', 29)
('Luxembourg', 10)
('Madagascar', 5)
('Malaysia', 28)
('Maldives', 2)
('Malta', 4)
('Mauritius', 2)
('Mexico', 88)
('Mongolia', 5)
('Montenegro', 2)
('Morocco', 17)
('Mozambique', 1)
('Myanmar', 1)
('Namibia', 1)
('Nepal', 30)
('Netherlands', 193)
('New Zealand', 60)
('Nicaragua', 4)
('Nigeria', 39)
('Norway', 60)
('Oman', 1)
('Other Country (Not Listed Above)', 9)
('Pakistan', 87)
('Panama', 5)
('Paraguay', 4)
('Peru', 15)
('Philippines', 40)
('Poland', 233)
('Portugal', 54)
('Qatar', 2)
('Republic of Korea', 3)
('Republic of Moldova', 4)
('Romania', 84)
('Russian Federation', 270)
('Rwanda', 1)
('Saudi Arabia', 15)
('Senegal', 1)
('Serbia', 31)
('Singapore', 37)
('Slovakia', 24)
('Slovenia', 31)
('Solomon Islands', 1)
('South Africa', 71)
('South Korea', 17)
('Spain', 203)
('Sri Lanka', 35)
('Sudan', 1)
('Swaziland', 1)
('Sweden', 129)
('Switzerland', 107)
('Syrian Arab Republic', 3)
('Taiwan', 16)
('Thailand', 24)
('The former Yugoslav Republic of Macedonia', 4)
('Togo', 1)
('Tunisia', 5)
('Turkey', 98)
('Turkmenistan', 1)
('Uganda', 6)
('Ukraine', 109)
('United Arab Emirates', 21)
('United Kingdom', 749)
('United Republic of Tanzania', 2)
('United States', 2350)
('Uruguay', 5)
('Uzbekistan', 5)
('Venezuela, Bolivarian Republic of...', 7)
('Viet Nam', 25)
('Yemen', 2)
('Zimbabwe', 4)

In [4]:
## Qual a quantidade usuários que moram em "United States" gostam de Windows?
session = Session()
result = session.execute(
    " SELECT p.nome, so.nome as sist_o, COUNT(r.index ) as qtd_usuarios "\
    " FROM respondente r "\
    " INNER JOIN sistema_operacional so ON r.sistema_operacional_index = so.index "\
    " INNER JOIN pais p ON p.index = r.pais_index  "\
    " WHERE p.nome = 'United States' and so.nome = 'Windows' "
    " GROUP BY p.nome, so.nome  "\
)
print('Quantidade de usuários que moram em "United States" e que gostam de Windows')
for row in result:
    print(row)

Quantidade de usuários que moram em "United States" e que gostam de Windows
('United States', 'Windows', 961)

In [5]:
## Qual a quantidade usuários que moram em "United States" gostam de Windows?
session = Session()
result = session.execute(
    " SELECT p.nome, so.nome as sist_o, avg(r.salario ) as media_salarios "\
    " FROM respondente r "\
    " INNER JOIN sistema_operacional so ON r.sistema_operacional_index = so.index "\
    " INNER JOIN pais p ON p.index = r.pais_index  "\
    " WHERE p.nome = 'Israel' and so.nome like 'Linux%'"\
    " GROUP BY p.nome, so.nome  "
    
)
print('Quantidade de usuários que moram em "Israel" e que gostam de Linux')
for row in result:
    print(row)

Quantidade de usuários que moram em "Israel" e que gostam de Linux
('Israel', 'Linux-based', 340024.042105263)

In [6]:
## Qual a média e o desvio padrão do salário dos usuários que usam Slack para cada tamanho de empresa disponível?
session = Session()
result = session.execute(
    " SELECT e.tamanho, avg(r.salario) as media_salarios, stddev(r.salario) as desvio_padrao "\
    " FROM respondente r "\
    " INNER JOIN respondenteferramenta_comunicacao rc ON r.index = rc.respondente_index "\
    " INNER JOIN ferramenta_comunicacao fc ON rc.ferramenta_comunicacao_index = fc.index "\
    " INNER JOIN empresa e ON r.empresa_index = e.index "\
    " WHERE fc.nome = 'Slack' "\
    " GROUP BY fc.nome, e.tamanho  "\
)
print('Média e o desvio padrão do salário dos usuários que usam Slack para cada tamanho de empresa disponível')
for row in result:
    print(row)

Média e o desvio padrão do salário dos usuários que usam Slack para cada tamanho de empresa disponível
('10 to 19 employees', 431637.844067796, 969431.147776181)
('5,000 to 9,999 employees', 531336.4, 1081373.94808142)
('100 to 499 employees', 544173.304514364, 1021569.27138269)
('1,000 to 4,999 employees', 543627.227906976, 910850.588865917)
('20 to 99 employees', 530620.316849016, 1115513.30733401)
('10,000 or more employees', 675286.100934579, 1358631.72718972)
('Fewer than 10 employees', 431384.513636364, 959331.281546808)
('-', 558804.731322506, 1100940.23910224)
('500 to 999 employees', 498070.863589744, 836141.795281831)